# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
