# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20170820_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
