# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Author notes follow:'),
        ),
    ]
