# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
